### ISSUE TITLE
Vmtk fails to build on OS X 10.11.6

### ISSUE THREAD

**Issue by diederikfr12** [vmtk/vmtk#170]
Hi I am trying to install Vmtk on my mac, but it keeps giving me an error when installing, could someone please help me?

Homebrew is up to date, system is ready to brew, no permission errors.

Bug reports:

I have an error while installing vmtk using homebrew. According to the installation instructions for MacOSX on vmtk.org I deleted: brew python, brew vtk, brew vmtk and brew insighttoolkit and afterwards tried to install vmtk, but I keep getting the same error message. I have Xcode 8.0 installed.

ld: warning: directory not found for option 'L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework'
[ 46%] Built target vtkvmtkComputationalGeometryPythonD
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

https://gist.github.com/cb304b0e7f8f573c07cbabc88731f0e0

**Comment by ffr** [comment]
I met the same problem, anyone can help?

**Comment by daron1337** [comment]
I've just built vmtk with brew from scratch using OSX Sierra.
`brew tap homebrew/science `
`brew install https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb`

I suggest to update XCode Command line tools with:

`xcode-select --install`

**Comment by mobernabeu** [comment]
I'm on macOS 10.12.6  and Xcode 9.0 and I'm encountering a similar problem to the one reported in this issue where the homebrew recipe tries to look for libraries from an old version of the Mac OS X SDK:

```
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework'
```

It should be using 10.13 rather than 10.12 in the `-L` option.

I tried @daron1337 suggested solution and I get the following error probably due to the variable `python_executable` being set to the empty string in lines 28-29 of `vmtk.rb`:

```
$ brew install https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb
######################################################################## 100.0%
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/vmtk/vmtk/archive/v1.3.2.tar.gz
==> Downloading from https://codeload.github.com/vmtk/vmtk/tar.gz/v1.3.2
######################################################################## 100.0%
sh: -c: command not found
sh: -c: command not found
sh: -c: command not found
Error: undefined local variable or method `dylib' for #<Formulary::FormulaNamespace9949859c16f4f3bd691dba25d3d29eb0::Vmtk:0x00000103a2a1d0>
/Users/mobernabeu/Library/Caches/Homebrew/Formula/vmtk.rb:56:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:143:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1912:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1889:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
```

Any suggestions?

**Comment by thangamnatarajan** [comment]
@mobernabeu did you manage to resolve the issue? I am having the same issue as well!

**Comment by mobernabeu** [comment]
@thangamnatarajan Unfortunately not yet. I was planning to upgrade to High Sierra and try again. Which version of macOS and Xcode are you on?

**Comment by thangamnatarajan** [comment]
I am trying to install vmtk on Mac Sierra - 10.12.6 with python 2.7 and the installation was as per the site (http://www.vmtk.org/download/). The Xcode version is 9.0.1. On looking at the make logs (/Users/username/Library/Logs/Homebrew/vmtk/02.make) the repeated error seems to be 

`/tmp/vmtk-20171024-56183-c2c73o/vmtk-1.3.1/vtkVmtk/Utilities/vtkvmtkITK/vtkvmtkITKArchetypeImageSeriesScalarReader.cxx:54:10: error: cannot initialize return object of type 'vtkDataArrayTemplate<double> *' with an rvalue of type 'vtkAOSDataArrayTemplate<ValueType> *' (aka 'vtkAOSDataArrayTemplate<double> *')`

Not sure how to go about it!

**Comment by lassoan** [comment]
VMTK builds on recent macOS versions (see github actions results).
