### ISSUE TITLE
run vmtkcenterlines.py have some errors

### ISSUE THREAD

**Issue by hongzhangMu** [vmtk/vmtk#197]
Traceback (most recent call last):
  File "vmtkcenterlines.py", line 671, in <module>
    main.Execute()
  File "C:\Python27\Lib\site-packages\vmtk\pypescript.py", line 643, in Execute
    pipe.Execute()
  File "C:\Python27\Lib\site-packages\vmtk\pype.py", line 275, in Execute
    scriptObject.Execute()
  File "C:\Python27\Lib\site-packages\vmtk\vmtkcenterlines.py", line 530, in Execute
    self.vmtkRenderer.Initialize()
  File "C:\Python27\Lib\site-packages\vmtk\vmtkrenderer.py", line 276, in Initialize
    self.RenderWindowInteractor.SetInteractorStyle(vtkvmtk.vtkvmtkInteractorStyleTrackballCamera())
AttributeError: 'module' object has no attribute 'vtkvmtkInteractorStyleTrackballCamera'
can you help me solve this problem? Thanks

**Comment by rlizzo** [comment]
Hi @hongzhangMu, this is solved in the latest vmtk release via anaconda python. feel free to reopen if there are other issues.
