### ISSUE TITLE
vmtkcenterlinesnetwork sometimes throws error given same input

### ISSUE THREAD

**Issue by kayarre** [vmtk/vmtk#312]
Sometimes when running I get an error and sometimes I don't using the same command:

it's the same `UnboundLocalError: local variable 'removeCellLength' referenced before assignment` error when it happens even though the execution command doesn't change. 

```
vmtkcenterlinesnetwork -ifile case2_vmtk_decimate_fill.vtp -delaunaytessellationfile case2_vmtk_decimate_fill_del2.vtu  -voronoidiagramfile case2_vmtk_decimate_fill_vor2.vtp -ofile case2_vmtk_decimate_fill_ctrlines2.vtp

Automatic piping vmtkcenterlinesnetwork
Parsing options vmtkcenterlinesnetwork
    SurfaceInputFileName = case2_vmtk_decimate_fill.vtp
    CenterlinesOutputFileName = case2_vmtk_decimate_fill_ctrlines2.vtp
    DelaunayTessellationOutputFileName = case2_vmtk_decimate_fill_del2.vtu
    VoronoiDiagramOutputFileName = case2_vmtk_decimate_fill_vor2.vtp
Explicit piping vmtkcenterlinesnetwork
Input vmtkcenterlinesnetwork members:
    Id = 0
    Disabled = 0
    Surface = None
    SurfaceInputFileName = case2_vmtk_decimate_fill.vtp
    vmtkRenderer = None
    CenterlinesOutputFileName = case2_vmtk_decimate_fill_ctrlines2.vtp
    DelaunayTessellationOutputFileName = case2_vmtk_decimate_fill_del2.vtu
    VoronoiDiagramOutputFileName = case2_vmtk_decimate_fill_vor2.vtp
Reading VTK XML surface file.
Generic Warning: In /home/sansomk/build/vmtk/build/VTK/Common/Core/vtkInstantiator.cxx, line 265
vtkInstantiator::CreateInstance was deprecated for VTK 8.1 and will be removed in a future version.

Executing vmtkcenterlinesnetwork ...
Progress: 100%Progress: 100%
Traceback (most recent call last):
  File "/home/sansomk/build/vmtk/build_dev/Install/lib/python3.6/site-packages/vmtk/pypeserver.py", line 46, in RunPypeProcess
    pipe.Execute()
  File "/home/sansomk/build/vmtk/build_dev/Install/lib/python3.6/site-packages/vmtk/pype.py", line 324, in Execute
    scriptObject.Execute()
  File "/home/sansomk/build/vmtk/build_dev/Install/lib/python3.6/site-packages/vmtk/vmtkcenterlinesnetwork.py", line 174, in Execute
    rescaledCellConnectivity = np.subtract(cellConnectivityList, removeCellLength, where=cellConnectivityList >= removeCellLength)
UnboundLocalError: local variable 'removeCellLength' referenced before assignment```

**Comment by kayarre** [comment]
Resolved by updates in #372
