### ISSUE TITLE
Failure to install on Linux Mint 18.1 using Anaconda

### ISSUE THREAD

**Issue by akdiem** [vmtk/vmtk#318]
Hi,

I've been trying to install vmtk on my Linux Mint 18.1 machine using Anaconda for quite a while now. If I try and install it using the command

`conda create -n foo -c vmtk python=3.6 itk vtk vmtk`

as stated on the Downloads page I get the following error when trying to use vmtkimagereader: 

```
# vmtkimagereader -ifile GNPs_Heart_Slices_Stack.tif --pipe vmtkimageviewer

Unexpected error: <class 'ModuleNotFoundError'>
Traceback (most recent call last):
  File "/home/alexandra/anaconda3/envs/vmtk/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: libjsoncpp.so.19: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandra/anaconda3/envs/vmtk/bin/vmtkimagereader", line 20, in <module>
    from vmtk import pypeserver
  File "/home/alexandra/anaconda3/envs/vmtk/lib/python3.6/site-packages/vmtk/pypeserver.py", line 16, in <module>
    import vtk
  File "/home/alexandra/anaconda3/envs/vmtk/lib/python3.6/site-packages/vtk/__init__.py", line 80, in <module>
    from .vtkIOParallel import *
  File "/home/alexandra/anaconda3/envs/vmtk/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
```

I get the same error if I first install itk and vtk from conda-forge and then vmtk from vmtk. conda list returns

```
# packages in environment at /home/alexandra/anaconda3/envs/vmtk:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
decorator                 4.3.0                      py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
future                    0.17.0                py36_1000    conda-forge
h5py                      2.8.0            py36h470a237_0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.0                      118  
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
itk                       4.13.0               h2f4ac57_1    vmtk
jedi                      0.13.1                py36_1000    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsoncpp                   1.8.1                h2d50403_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libcurl                   7.61.0               h1ad7b7a_0  
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libogg                    1.3.2                h470a237_1    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtheora                 1.1.1                h470a237_1    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libvorbis                 1.3.5                h470a237_1    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
llvm                      3.3                           0  
lz4-c                     1.8.1.2                       0    conda-forge
mesa                      10.5.4                        0  
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.12.1           py36he24570b_1  
numpy-base                1.15.0           py36h3dfced4_0  
openssl                   1.0.2p               h470a237_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       18.1                  py36_1000    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pygments                  2.2.0                      py_1    conda-forge
python                    3.6.1                         2  
readline                  6.2                           2  
setuptools                40.5.0                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.13.0                        1    conda-forge
system                    5.8                           2  
tbb                       2019.1               h2d50403_0    conda-forge
tk                        8.5.18                        0  
traitlets                 4.3.2                 py36_1000    conda-forge
vmtk                      1.4.0            py36hfe14cac_1    vmtk
vtk                       8.1.0           py36h969b564_201  
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by jiehyunjkim** [comment]
Hi, I got similar problem. 

I installed the environment by
```conda config --env --set restore_free_channel true```
```conda install vmtk -c vmtk```

And when I try to run ```vmtklevelsetsegmentation -ifile image_volume_voi.vti -ofile level_sets.vti
``` with proper filename, I got an error message as:
```
Unexpected error: <type 'exceptions.ImportError'>
Traceback (most recent call last):
  File "/home/jiehyun.kim001/miniconda3/envs/vmtk/bin/vmtklevelsetsegmentation", line 20, in <module>
    from vmtk import pypeserver
  File "/home/jiehyun.kim001/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/pypeserver.py", line 16, in <module>
    import vtk
  File "/home/jiehyun.kim001/miniconda3/envs/vmtk/lib/python2.7/site-packages/vtk/__init__.py", line 33, in <module>
    from .vtkRenderingOpenGL2 import *
  File "/home/jiehyun.kim001/miniconda3/envs/vmtk/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL2.py", line 9, in <module>
    from vtkRenderingOpenGL2Python import *
ImportError: No module named vtkRenderingOpenGL2Python
```

**Comment by lassoan** [comment]
Windows, linux, macOS wheels are now published on PyPI for 1.5.0.
