### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by reirei2021** [vmtk/vmtk#360]
Hello,

I have installed vmtk, and it went well with no issues. however when I want to use any script I get this error:

Unexpected error: <class 'ModuleNotFoundError'>
Traceback (most recent call last):
  File "/home/anaconda3/envs/vascular_modeling_toolkit/lib/python3.6/site-packages/vtk/vtkRenderingOpenGL2.py", line 5, in <module>
    from .vtkRenderingOpenGL2Python import *
ImportError: libLLVM-3.3.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/vascular_modeling_toolkit/bin/vmtkimagereader", line 20, in <module>
    from vmtk import pypeserver
  File "/home/anaconda3/envs/vascular_modeling_toolkit/lib/python3.6/site-packages/vmtk/pypeserver.py", line 16, in <module>
    import vtk
  File "/home/anaconda3/envs/vascular_modeling_toolkit/lib/python3.6/site-packages/vtk/__init__.py", line 33, in <module>
    from .vtkRenderingOpenGL2 import *
  File "/home/anaconda3/envs/vascular_modeling_toolkit/lib/python3.6/site-packages/vtk/vtkRenderingOpenGL2.py", line 9, in <module>
    from vtkRenderingOpenGL2Python import *
ModuleNotFoundError: No module named 'vtkRenderingOpenGL2Python'

I tried to install  libLLVM-3.3, but there's no such version anymore.

**Comment by dhruvshah01** [comment]
Hey! I was using vmtk for one of my projects and got the same error. Did you found a solution or any other tweaks? Please let me know.

**Comment by lassoan** [comment]
Windows, linux, macOS wheels are now published on PyPI for 1.5.0.
