### ISSUE TITLE
dll load failed

### ISSUE THREAD

**Issue by zhang-qiang-github** [vmtk/vmtk#422]
I am build vmtk from source code. The VS compiling and building success. Then, I want to build python wrapper, and the setting of cmake is: 

![image](https://user-images.githubusercontent.com/29271051/161423298-0ed1845c-765a-49c6-b8e4-b0840692c8cd.png)

After building, I copy `build/install/lib/python3.7/site-packages/vmtk` to `Anaconda3/envs/VMTK/Lib/site-packages/`. 

Then, I enter python environment, and want to import `vtkvmtk`, a bug is reported:

```
>>> import vmtk
>>> from vmtk import vtkvmtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\VMTK\lib\site-packages\vmtk\vtkvmtk.py", line 9, in <module>
    from .vtkvmtkCommonPython import *
ImportError: DLL load failed
```

However, I can find `vtkvmtkCommonPython.pyd` in `Anaconda3/envs/VMTK/Lib/site-packages/vmtk`:

![image](https://user-images.githubusercontent.com/29271051/161424021-f0544739-82ae-4168-b9e9-f9f2117cb2ad.png)

What's wrong with my process?

Any suggestion is appreciated~~~

My environment is:

```
win 10
vs 2019
cmake 3.22.1
vtk 9.0.1
itk 5.2.1
vmtk: the lastest code SHA-1: 27e3784dde5c2e8ad6a4ef21edfd50c72763fcdf

```

**Comment by lassoan** [comment]
This typically happens when a required DLL is not found during import (for example, you haven't copied VTK and ITK DLLs into the VMTK folder). You can use Process Monitor utility to check which DLL was not found.

**Comment by ramtingh** [comment]
you're using Anaconda, so either install it from conda-forge (` conda install -c conda-forge vmtk `) or look at the anaconda build script in this repository (https://github.com/vmtk/vmtk/tree/master/distribution).

**Comment by lassoan** [comment]
Windows, linux, macOS wheels are now published on PyPI for 1.5.0.
