### ISSUE TITLE
[Bug] vmtk window freezes

### ISSUE THREAD

**Issue by karabelaselias** [vmtk/vmtk#425]
Dear all,
I operate Ubuntu 20.04 LTS with the nvidia-drivers 510 and cuda-10. First things first, I also use slicer which works fine and also the vmtk module operates well in it.

However, there are some things from vmtk I would like to use like the adaptive meshing and the boundary layers and the automatic surface capping. So I thought I need vmtk standalone

I compiled vmtk master according to the website and everything works out fine, however when I invoke the command

```
vmtksurfacereader -ifile foo.vtp --pipe vmtkcenterlines --pipe vmtkendpointextractor --pipe vmtkbranchclipper --pipe vmtksurfaceconnectivity -cleanoutput 1 --pipe vmtksurfacewriter -ofile foo_ct.vtp
```
as stated [here](http://www.vmtk.org/tutorials/SurfaceForMeshing.html) I run into the following issue:

First window pops up asking me to select seed points. I place one and press "q" to continue placing target points. However, the window refreshes and then freezes without any debug info in the console or apparent segfault (checked dmesg and syslog).

Has anyone else encountered a similar issue? Has this something to do with the nvidia drivers?

Best regards
Elias

**Comment by isaiahchua** [comment]
Hi all, 

I run into the same issue using the same command both when running vmtk straight from the terminal and with python scripts. This only happens with the vmtk development version and not with the build installed from Conda. Any solution found for this issue? Thanks in advance.

OS: Ubuntu 20.04.2 LTS
Python version used when building vmtk: 3.9.12

Regards
Isaiah

**Comment by ramtingh** [comment]
I see, The one hanging is ` vmtkcenterlines  ` with the default seed selector?

**Comment by karabelaselias** [comment]
Exactly

**Comment by ramtingh** [comment]
Hmm, I can't seem to reproduce that on windows at least. I'll try later on ubuntu

**Comment by isaiahchua** [comment]
Hi @ramtingh , I've tried to install vmtk 1.5 using conda-forge as suggested on this page:
https://discourse.slicer.org/t/no-module-named-vtkmodules-vtkcommoncore/21854/7

These are the commands I ran to create the vmtk version 1.5 environments in both MacOS and Ubuntu:
`conda update conda anaconda-client`
`conda config --set restore_free_channel true`
`conda create -n vmtk2 -c conda-forge itk vtk vmtk=1.5`

On MacOS 12.2.1 it renders the windows correctly and I am able to run my python code up to when I use vmtkdistancetocenterlines where it breaks down with the error message below. Running the vmtkdistancetocenterlines directly through the terminal without any other pypes leads to the same error:

Traceback (most recent call last):
  File "/Users/isaiah/miniconda3/envs/vmtk2/bin/vmtk", line 44, in <module>
    pipe.Execute()
  File "/Users/isaiah/miniconda3/envs/vmtk2/lib/python3.9/site-packages/vmtk/pype.py", line 321, in Execute
    scriptObject.PrintInputMembers()
  File "/Users/isaiah/miniconda3/envs/vmtk2/lib/python3.9/site-packages/vmtk/pypescript.py", line 247, in PrintInputMembers
    self.PrintMembers(self.InputMembers)
  File "/Users/isaiah/miniconda3/envs/vmtk2/lib/python3.9/site-packages/vmtk/pypescript.py", line 233, in PrintMembers
    memberValue = self.__getattribute__(memberName)
AttributeError: 'vmtkDistanceToCenterlines' object has no attribute 'UseRadiusThreshold'

On Ubuntu 20.04.02 LTS, it runs the code but the windows do not pop up. E.g. when I run `vmtk vmtksurfaceviewer -ifile foo.stl` from the terminal the messages still print but the window to interact with the surface foo.stl doesn't pop up.

See attached for the list of installed packages in both systems.

[vmtk_macos.txt](https://github.com/vmtk/vmtk/files/8674991/vmtk_macos.txt)
[vmtk_ubuntu.txt](https://github.com/vmtk/vmtk/files/8674992/vmtk_ubuntu.txt)

**Comment by ramtingh** [comment]
@isaiahchua Thanks for the reports, the osx problems should be fixed by the linked pull request. It'll probably take some time for that to be merged and conda packages to update, so in the mean time you can manually add these two lines (https://github.com/vmtk/vmtk/pull/428/commits/e5d08bc53c9ee41659eb8e68abf603e513938d08)

Ubuntu is going to be more difficult to figure out, I guess something is going wrong interacting with the rendering backend on linux

**Comment by lassoan** [comment]
For any interactive work (specify inputs, visualize outputs) I would not recommend these extremely limited, low-level pypes. Instead, you can [use VMTK in a Python environment that offers proper GUI, such as 3D Slicer](https://github.com/vmtk/SlicerExtension-VMTK/#the-vmtk-extension-for-3d-slicer).

**Comment by isaiahchua** [comment]
@ramtingh thanks after adding the two lines, everything works as expected on Mac. May I know if a solution for the issues on Linux is currently in the works? And may I have a list of required packages and their dependencies to compare with the list I sent in my previous comment? Thanks again

@lassoan thanks for your suggestion. Do you mean I can run my python file which uses vmtkscripts directly using 3D Slicer?

**Comment by lassoan** [comment]
You can use all VMTK classes using standard Python interface in Slicer - the same way as the pypes script use VMTK.

I much prefer this pure Python scripting over the mixed shell scripting + Python scripting that pypes require.

**Comment by isaiahchua** [comment]
@lassoan 

Thanks I've installed slicer and the vmtk extension. How do I write and execute a python script which makes use of vmtk classes on slicer? I tried to import vmtk directly on the standard Python interface but the module was not found. Do I need to setup the super-build to access all the vmtk classes? 

If you could direct me to some resources specific to this inquiry it would be greatly appreciated as there is a wealth of documentation on slicer that can be hard to sift through. Thanks again.

**Comment by lassoan** [comment]
After you install the VMTK extension in Slicer, you can import each VMTK component like this:

https://github.com/vmtk/SlicerExtension-VMTK/blob/b280bd8471e4036282be3c7402c37e7d099d0d3e/ExtractCenterline/ExtractCenterline.py#L445-L446

This Slicer module source code also serves as an example of how to get inputs from Slicer GUI and how to write VMTK processing results into Slicer nodes for visualization.

**Comment by lassoan** [comment]
Windows, linux, macOS wheels are now published on PyPI for 1.5.0.
