### ISSUE TITLE
AttributeError when using vmtkcenterlines

### ISSUE THREAD

**Issue by JIsaacW** [vmtk/vmtk#445]
Hi, I am new in vmtk.
I find an attributeError when I use vmtkcenterlines,

My input:
`vmtkcenterlines -ifile 0186Model_capped.vtp -ofile centerline.vtp`

The terminal output:
```
Automatic piping vmtkcenterlines
Parsing options vmtkcenterlines
    SurfaceInputFileName = 0186Model_capped.vtp
    CenterlinesOutputFileName = centerline.vtp
Explicit piping vmtkcenterlines
Input vmtkcenterlines members:
    Id = 0
    Disabled = 0
    Surface = None
    SurfaceInputFileName = 0186Model_capped.vtp
    SeedSelectorName = pickpoint
    SourceIds = []
    TargetIds = []
    SourcePoints = []
    TargetPoints = []
    AppendEndPoints = 0
    CheckNonManifold = 0
    FlipNormals = 0
    CapDisplacement = 0.0
    DelaunayTolerance = 0.001
    RadiusArrayName = MaximumInscribedSphereRadius
    AppendEndPoints = 0
    Resampling = 0
    ResamplingStepLength = 1.0
    DelaunayTessellation = None
    SimplifyVoronoi = 0
    UseTetGen = 0
    TetGenDetectInter = 1
    CostFunction = 1/R
    vmtkRenderer = None
    CenterlinesOutputFileName = centerline.vtp
    DelaunayTessellationOutputFileName = 
    VoronoiDiagramOutputFileName = 
Reading VTK XML surface file.
Executing vmtkcenterlines ...
Traceback (most recent call last):
  File "/home/isaac/Program/anaconda3/envs/vmtkEnv1/lib/python3.6/site-packages/vmtk/pypeserver.py", line 46, in RunPypeProcess
    pipe.Execute()
  File "/home/isaac/Program/anaconda3/envs/vmtkEnv1/lib/python3.6/site-packages/vmtk/pype.py", line 324, in Execute
    scriptObject.Execute()
  File "/home/isaac/Program/anaconda3/envs/vmtkEnv1/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 529, in Execute
    self.vmtkRenderer.Initialize()
  File "/home/isaac/Program/anaconda3/envs/vmtkEnv1/lib/python3.6/site-packages/vmtk/vmtkrenderer.py", line 315, in Initialize
    self.RenderWindowInteractor.SetInteractorStyle(vtkvmtk.vtkvmtkInteractorStyleTrackballCamera())
AttributeError: module 'vmtk.vtkvmtk' has no attribute 'vtkvmtkInteractorStyleTrackballCamera'

```

I wonder if there are something wrong in my installation.
My system is ubuntu 18.04, and I used conda to install vmtk, referring the tutorials in http://www.vmtk.org/download/
Thanks.

**Comment by lassoan** [comment]
Most of us use VMTK for processing, therefore the rendering and interaction features are largely untested.

The vtkvmtkInteractorStyleTrackballCamera class is still present in VMTK, so probably it is just some error in packaging or importing the class. If you can figure out a fix and submit a pull request then we should be able to review and merge it.

**Comment by JIsaacW** [comment]
Thankd, I will try it later.

**Comment by JIsaacW** [comment]
Thanks, I will try it later.
