### ISSUE TITLE
vmtkbranchextractor not working properly on linux?

### ISSUE THREAD

**Issue by perecanals** [vmtk/vmtk#450]
Hi,

I recently updated my conda environments on my machines (I work with both Mac and Linux). Among my packages there was VMTK (1.5.0) installed using conda-forge. In Mac (Ventura 13.1) I am using Python 3.10.8, and on Linux (Ubuntu 22.04) Python 3.10.9, and the vmtk commands are working perfectly in Mac, while on Linux I am getting this error using the same code on the same data.

The command:
```
vmtkbranchextractor -ifile /home/vhir/github/arterial/tests/circular_centerlines/example/centerlines/centerlines0.vtk -ofile /home/vhir/github/arterial/tests/circular_centerlines/example/branch_models/branch_model0.vtk -radiusarray Radius
```
The terminal output:
```
Automatic piping vmtkbranchextractor
Parsing options vmtkbranchextractor
    CenterlinesInputFileName = /home/vhir/github/arterial/tests/circular_centerlines/example/centerlines/centerlines0.vtk
    RadiusArrayName = Radius
    CenterlinesOutputFileName = /home/vhir/github/arterial/tests/circular_centerlines/example/branch_models/branch_model0.vtk
Explicit piping vmtkbranchextractor
Input vmtkbranchextractor members:
    Id = 0
    Disabled = 0
    Centerlines = None
    CenterlinesInputFileName = /home/vhir/github/arterial/tests/circular_centerlines/example/centerlines/centerlines0.vtk
    RadiusArrayName = Radius
    GroupIdsArrayName = GroupIds
    CenterlineIdsArrayName = CenterlineIds
    TractIdsArrayName = TractIds
    BlankingArrayName = Blanking
    CenterlinesOutputFileName = /home/vhir/github/arterial/tests/circular_centerlines/example/branch_models/branch_model0.vtk
Reading VTK surface file.
Executing vmtkbranchextractor ...
Traceback (most recent call last):
  File "/home/vhir/anaconda3/envs/arterial_env/lib/python3.10/site-packages/vmtk/pypeserver.py", line 48, in RunPypeProcess
    pipe.Execute()
  File "/home/vhir/anaconda3/envs/arterial_env/lib/python3.10/site-packages/vmtk/pype.py", line 324, in Execute
    scriptObject.Execute()
  File "/home/vhir/anaconda3/envs/arterial_env/lib/python3.10/site-packages/vmtk/vmtkbranchextractor.py", line 63, in Execute
    branchExtractor.SetInputData(self.Centerlines)
AttributeError: 'vtkvmtkComputationalGeometry.vtkvmtkCenterlineBran' object has no attribute 'SetInputData'
```
I went to check the code of the vmtkbranchexractor.py file at the anaconda3/envs/env_name/lib.python3.10/site-packages/vmtk direcory and it looks the same to me in both systems.

Any ideas on what is happening here? I have already tried to uninstall vmtk and install it back and I get the same error.

**Comment by perecanals** [comment]
Update: creating a new environmen with python 3.9.16 solved it. Perhaps stay away from python 3.10?
