### ISSUE TITLE
SetFontSize argument 1: integer argument expected, got float

### ISSUE THREAD

**Issue by jiehyunjkim** [vmtk/vmtk#460]
I tried to give input data as nrrd, vtk, vti but all returns same problem as below:
```
(vmtk) ...:~$ vmtklevelsetsegmentation -ifile ~/62.img.vti -ofile level_sets.vti

Automatic piping vmtklevelsetsegmentation
Parsing options vmtklevelsetsegmentation
    ImageInputFileName = /62.img.vti
    LevelSetsOutputFileName =/level_sets.vti
Explicit piping vmtklevelsetsegmentation
Input vmtklevelsetsegmentation members:
    Id = 0
    Disabled = 0
    Image = None
    ImageInputFileName =/62.img.vti
    FeatureImage = None
    FeatureImageInputFileName = 
    InitializationImage = None
    InitializationImageInputFileName = 
    InitialLevelSets = None
    InitialLevelSetsInputFileName = 
    LevelSets = None
    LevelSetsInputFileName = 
    LevelSetsType = geodesic
    FeatureImageType = gradient
    NegateForInitialization = 0
    SigmoidRemapping = 0
    IsoSurfaceValue = 0.0
    DerivativeSigma = 0.0
    FeatureDerivativeSigma = 0.0
    UpwindFactor = 1.0
    FWHMRadius = [1.0, 1.0, 1.0]
    FWHMBackgroundValue = 0.0
    NumberOfIterations = 0
    PropagationScaling = 0.0
    CurvatureScaling = 0.0
    AdvectionScaling = 1.0
    EdgeWeight = 0.0
    SmoothingIterations = 5
    SmoothingTimeStep = 0.1
    SmoothingConductance = 0.8
    vmtkRenderer = None
    LevelSetsOutputFileName = /level_sets.vti
    FeatureImageOutputFileName = 
Reading VTK XML image file.
Spacing 0.679688 0.679688 1.500000
Origin -173.660156 -356.660156 1019.000000
Dimensions 512 512 268
Executing vmtklevelsetsegmentation ...
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/pypeserver.py", line 46, in RunPypeProcess
    pipe.Execute()
  File "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/pype.py", line 324, in Execute
    scriptObject.Execute()
  File "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/vmtklevelsetsegmentation.py", line 285, in Execute
    self.vmtkRenderer.Initialize()
  File "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/vmtkrenderer.py", line 336, in Initialize
    self.TextActor.GetTextProperty().SetFontSize(fontSize)
TypeError: SetFontSize argument 1: integer argument expected, got float
```

Anyone have idea how to fix it?

**Comment by enjolras1949** [comment]
same problem here

**Comment by lassoan** [comment]
Have you tried to go to "/home/username/miniconda3/envs/vmtk/lib/python2.7/site-packages/vmtk/vmtkrenderer.py", line 336, and add `int()`? 

Original:

    self.TextActor.GetTextProperty().SetFontSize(fontSize)

New:

    self.TextActor.GetTextProperty().SetFontSize(int(fontSize))

If it fixes the issue then please submit a pull request with this change.

I don't use the vmtkrenderer (use 3D Slicer for all interactive GUI, as it is just so much nicer and more powerful), but I don't mind merging this change if that fixes a problem for you.

**Comment by ramtingh** [comment]
I think this is already converted to an int https://github.com/vmtk/vmtk/blob/master/vmtkScripts/vmtkrenderer.py#L331

@jiehyunjkim What version are you using as I assume python 2.7 versions would be very old

**Comment by jiehyunjkim** [comment]
@ramtingh Thank you! I update to python 3.5 and it solve that problem. However, then I see 

```
 ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 797
vtkOSOpenGLRenderWindow (0x163a690): GL version 2.1 with the gpu_shader4 extension is not supported by your graphics driver but is required for the new OpenGL rendering backend. Please update your OpenGL driver. If you are using Mesa please make sure you have version 10.6.5 or later and make sure your driver in Mesa supports OpenGL 3.2.

```

I found solution here: https://groups.google.com/g/vmtk-users/c/IbVEv2p64Tc/m/XWNDt88RAwAJ
Then I see 

```
ModuleNotFoundError: No module named 'vtkCommonCorePython'
```

Any idea?

**Comment by jiehyunjkim** [comment]
This is how I solve some steps:

Probelm 1:
```
ImportError: libtbb.so.2: cannot open shared object file: No such file or directory
```
Solution 1:
```
conda install tbb=2020.2
```
Problem 2:
```
ImportError: libjsoncpp.so.19: cannot open shared object file: No such file or directory
```
Solution 2:
```
conda install jsoncpp=1.8.3
```

Then I faced this issue:
```
ERROR: In ../Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 1223
vtkXOpenGLRenderWindow (0x2c099f0): bad X server connection. DISPLAY=(vmtk3) 
```

**Comment by jiehyunjkim** [comment]
This command line solve the problem!

```
conda install -c conda-forge libstdcxx-ng
```
