### ISSUE TITLE
Unable to install VMTK on Linux server

### ISSUE THREAD

**Issue by YouqiongLiu** [vmtk/vmtk#472]
Installation methods：conda create -n foo -c vmtk python=3.6 itk vtk vmtk
It shows that the installation was successful, but run the following program

from vmtk import vmtkmeshreader
mesh_reader = vmtkmeshreader.vmtkMeshReader()

The error message is as follows：
Traceback (most recent call last):
  File "ComputingCenterlines.py", line 1, in <module>
    from vmtk import vmtkmeshreader
  File "/home/wangtai/anaconda3/envs/vmtk_env/lib/python3.6/site-packages/vmtk/vmtkmeshreader.py", line 18, in <module>
    import vtk
  File "/home/wangtai/anaconda3/envs/vmtk_env/lib/python3.6/site-packages/vtk/__init__.py", line 33, in <module>
    from .vtkRenderingOpenGL2 import *
  File "/home/wangtai/anaconda3/envs/vmtk_env/lib/python3.6/site-packages/vtk/vtkRenderingOpenGL2.py", line 9, in <module>
    from vtkRenderingOpenGL2Python import *
ModuleNotFoundError: No module named 'vtkRenderingOpenGL2Python'

**Comment by lassoan** [comment]
VMTK is now available on PyPI.
