### ISSUE TITLE
vtkvmtk error

### ISSUE THREAD

**Issue by keisuke0117** [vmtk/vmtk#474]
When I run the command:
python /mnt/d/vmtk/vmtkApps/CerebralAneurysms/ParentVesselReconstruction/patchandinterpolatecenterlines.py directoryPath id1 lateral
I get the following error:
Traceback (most recent call last):
  File "/mnt/d/vmtk/vmtkApps/CerebralAneurysms/ParentVesselReconstruction/patchandinterpolatecenterlines.py", line 8, in <module>
    from vtkVmtk import vtkvmtk
  File "/mnt/d/vmtk/vtkVmtk/vtkvmtk.py", line 9, in <module>
    from .vtkvmtkCommonPython import *
ModuleNotFoundError: No module named 'vtkVmtk.vtkvmtkCommonPython'

However, upon checking, I found that there is no vtkvmtkCommonPython module within the vtkvmtk folder. In fact, almost all of the modules referenced in vtkvmtk.py are missing, which is causing errors.

Has anyone else faced a similar issue? I would appreciate any advice on how to resolve this.

**Comment by lassoan** [comment]
Windows, linux, macOS wheels are now published on PyPI for 1.5.0. The scripts should work correctly now.
